language: python
python:
- '2.7'

cache:
  directories:
  - /home/travis/.rvm
  - /home/travis/.cache/pip
  - /home/travis/virtualenv

install: make install

before_script: make before_script

script: make script
