---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: centos/systemd
    command: /usr/sbin/init
    privileged: True
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../roles
  inventory:
    group_vars:
      all:
        common_users:
          - name: fbl01
            comment: Fred Bloggs
            email: fred.bloggs@example.com
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
