---
# tasks file for common
- name: Install packages
  package:
    name: "{{ item }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  with_items:
  - ntp

- name: Configure users
  user:
    comment: "{{ item.comment | default('') }}"
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  when: common_users is defined
  with_items: "{{ common_users }}"
  no_log: True

- name: Configure NTP
  template:
    src: ntp/ntp.conf.j2
    dest: /etc/ntp.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart ntp daemon
